name: Trigger Build on Main Repo

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build in main repository
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/Bondaliname/my-project-infrastructure/dispatches \
            -d '{"event_type":"frontend-updated","client_payload":{"ref":"${{ github.ref }}","sha":"${{ github.sha }}"}}'
      
      - name: Summary
        run: |
          echo "Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
